title: "Juan C. Lozano"
description: "Researcher in Cyber-Physical Systems Security, Power Grid Protocols, and Applied ML"
url: "https://juanclozano.com"
baseurl: ""

theme: minima

header_pages:
  - index.md
  - research.md
  - publications.md
  - teaching.md
  - cv.md
  - contact.md

markdown: kramdown

minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/jclozanoca" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/juan-camilo-lozano-carrillo-752876113/" }

# Optional but recommended
plugins:
  - jekyll-feed
